# Chapter 3

Exercises from Andrew Trask's _Grokking Deeplearning_

## What is a neural network

In [2]:
weight = 0.1

def neural_network(X, w):
    return X * w

In [3]:
num_toes = [8.5, 9.5, 10, 9]
X_test = num_toes[0]
pred = neural_network(X_test, weight)
pred

0.8500000000000001

Congrats, the worlds dumbest single-node perceptron

...lets try one with multiple inputs

In [16]:
def neural_network(x, weights):
    pred = w_sum(x, weights)
    return pred

def w_sum(a, b):
    if len(a) != len(b):
        raise ValueError
    output = 0
    for val, weight in zip(a,b):
        output += val * weight
    return output


In [18]:
toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

inputs = [toes[0], wlrec[0], nfans[0]]
weights = [.1, .2, 0]

neural_network(inputs, weights)

0.9800000000000001

this sucks without vectors, so lets implement some vector ops

In [20]:
from typing import Iterable

In [25]:
def __raise_for_len_mismatch__(a, b):
    """Return a value error if these two vectors aren't the same lenght"""
    if len(a) != len(b):
        return ValueError
    assert all(map(type, a)) == all(map(type, b))

def elementwise_multiplication(a: Iterable[float], b: Iterable[float]):
    __raise_for_len_mismatch__(a,b)
    return [i * j for i, j in zip(a,b)]

def elementwise_addition(a, b):
    __raise_for_len_mismatch__(a,b)
    return [i + j for i, j in zip(a,b)]

def vector_sum(a):
    return sum(a)

def vector_avg(a):
    return vector_sum(a) / len(a)

So now we can make a dot product, which describes the similarity of two vectors

In [26]:
def dot_product(a, b):
    __raise_for_len_mismatch__(a, b)
    return vector_sum(
        elementwise_multiplication(
            a,b
        )
    )

In [29]:
dot_product(
    [0,1,0,1],
    [0,1,0,1]
)

2

In [31]:
dot_product(
    [0, 0, 0, 1],
    [1, 0, 0, 1]
)

1

How about with multiple outputs?

In [32]:
def neural_network(input, weights):
    return elementwise_multiplication(input, weights)

In [33]:
win_loss_record = [.65, .8, .8, .9]
neural_network(win_loss_record, weights)

[0.065, 0.16000000000000003, 0.0]

Well that's pretty neato

In [37]:
def multiplex_network(input, weights):
    return vec_mat_mul(input, weights)

def vec_mat_mul(vector, matrix):
    assert len(vector) == len(matrix)
    return [dot_product(vector, weights) for weights in matrix]

In [39]:
weights = [
    [0.1, 0.1, -0.3],
    [0.1, 0.2, 0.0],
    [0.0, 1.3, 0.1]
]

multiplex_network(
   [8.5, 0.65, 1.2], weights
)

[0.555, 0.9800000000000001, 0.9650000000000001]

## numpy primer, cause It's been a while

In [40]:
import numpy as np

In [46]:
a = np.array([0,1,2,3])
b = np.array([4,5,6,7])
c = np.array([
    [0,1,2,3],
    [4,5,6,7]
])
d = np.zeros((2,4))
e = np.random.rand(2,5)

In [47]:
a

array([0, 1, 2, 3])

In [48]:
b

array([4, 5, 6, 7])

In [49]:
c

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [50]:
d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [51]:
e

array([[0.29263815, 0.09105858, 0.41895689, 0.89905801, 0.15790361],
       [0.54224045, 0.12202438, 0.04154941, 0.03993777, 0.51715568]])

In [52]:
a*0.1

array([0. , 0.1, 0.2, 0.3])

In [53]:
c*0.2

array([[0. , 0.2, 0.4, 0.6],
       [0.8, 1. , 1.2, 1.4]])

In [54]:
a*c

array([[ 0,  1,  4,  9],
       [ 0,  5, 12, 21]])

In [55]:
b*c

array([[ 0,  5, 12, 21],
       [16, 25, 36, 49]])

In [56]:
a * e

ValueError: operands could not be broadcast together with shapes (4,) (2,5) 